### PR TITLE
fix: convert any usage into  or typed version

### PR DESCRIPTION
**Pull request by berendsliedrecht**
Converted most any usage to unknown. Not the best fix in the world, but to make it fully properly typed I need some more time.

### CODE REVIEW

**Comment by cre8** [comment]
@berendsliedrecht build is failing, do you need help with this?: https://github.com/openwallet-foundation-labs/sd-jwt-js/actions/runs/8003556836/job/21859109338?pr=80#step:7:146

**Comment by berendsliedrecht** [comment]
@cre8 Should be fixed now.

**Review by cre8 — APPROVED** [review]
LGTM

**Review by lukasjhan — APPROVED** [review]
Good :)

**Pull request merged**
