### PR TITLE
style: formatted code with biome

### PR DESCRIPTION
**Pull request by cre8**
adding biome to the github action, also formatting the files

### CODE REVIEW

**Review by berendsliedrecht — DISMISSED** [review]

**Comment by cre8** [comment]
When I run `npx biome ci .` locally it works fine. But the run in the action fails.

**Review by berendsliedrecht — APPROVED** [review]

**Comment by lukasjhan** [comment]
@cre8 sorry for the conflict.
due to merging #80. ``` is change to `'` in examples/core-example/decode.ts
Please resolve it.

**Review by lukasjhan — APPROVED** [review]
Good :)

**Comment by lukasjhan** [comment]
{"error": "Server Error (500)"} in failed action. Do you have an idea why it failed?

**Review by lukasjhan — APPROVED** [review]

**Pull request merged**
