### PR TITLE
type: remove rsa type in jwk

### PR DESCRIPTION
**Pull request by lukasjhan**
I accidentally forgot to remove the rsa type.

### CODE REVIEW

**Review by zustkeeper — APPROVED** [review]

**Comment by berendsliedrecht** [comment]
What was the reason for removing rsa here?

**Comment by lukasjhan** [comment]
@berendsliedrecht We discussed this issue in #130. I thought @cre8 removed and approved it but It was not actually removed, So I opened this PR

**Comment by berendsliedrecht** [comment]
Ahh okay, yeah that makes sense! If we fully want to delete it would should also get rid of the `n` and `e` fields. I don't think they are used by any other algo, but they are the main components for RSA keys.

**Comment by lukasjhan** [comment]
> Ahh okay, yeah that makes sense! If we fully want to delete it would should also get rid of the `n` and `e` fields. I don't think they are used by any other algo, but they are the main components for RSA keys.

Oh I see, I'll prepare PR for that :)

**Comment by cre8** [comment]
I think we could use the definition from the `dom.lib.ts` and just copy it. Would this solve all the edge cases?

**Comment by cre8** [comment]
I would add the fields again. Just because some organisation say RSA usage is not safe anymore, it is still used out there ;)

With my comments on 130 I intended that we have just the `Jsonwebkey` interface, but inside it all attributes to cover different keys like in the lib.dom.ts

**Comment by lukasjhan** [comment]
@cre8 @berendsliedrecht I opened a PR for restoring rsa field in JWK. #137

**Pull request merged**
