### PR TITLE
[#28]Add github link to npm

### PR DESCRIPTION
**Pull request by lukasjhan**
Issue: #28 

## Purpose

Add links to npm(package.json)

1. github repo link
2. issue link
3. docs(wiki) link

### CODE REVIEW

**Review by pensivej — COMMENTED** [review]
I don't think receiving bugs through personal email is a good policy

**Comment by lukasjhan** [comment]
> I don't think receiving bugs through personal email is a good policy

Then which emails do you want to use? @pensivej

**Comment by pensivej** [comment]
> > I don't think receiving bugs through personal email is a good policy
> 
> Then which emails do you want to use? @pensivej

Is `email` required field?
If not, I recommend just now using it.
If so, I think we need more discussion.

**Comment by lukasjhan** [comment]
> > > I don't think receiving bugs through personal email is a good policy
> > 
> > 
> > Then which emails do you want to use? @pensivej
> 
> Is `email` required field? If not, I recommend just now using it. If so, I think we need more discussion.

It's not required. I'll remove it :)

**Review by pensivej — APPROVED** [review]
LGTM

**Pull request merged**
