### PR TITLE
feat: es crypto features to nodejs and browser

### PR DESCRIPTION
**Pull request by lukasjhan**
I implement 

- Ed25519 and ES256 signer and verifier for crypto-nodejs
- ES256 signer and verifier for crypto-browser (not tested)

### CODE REVIEW

**Comment by lukasjhan** [comment]
hmm.. I have no idea how to test browser crypto subtle module. Any ideas?

**Comment by cre8** [comment]
> hmm.. I have no idea how to test browser crypto subtle module. Any ideas?

It depends on the test framework and I read that vitest with jsdom does not support the crypto apis... I tested it manually by running a crypress test with angular because then it is using a chrome instance in the background

**Comment by lukasjhan** [comment]
@cre8 Yeah, we definitely use some framework that use headless chrome(or other browser)

How about trying this? https://playwright.dev/

**Comment by cre8** [comment]
> @cre8 Yeah, we definitely use some framework that use headless chrome(or other browser)
> 
> How about trying this? https://playwright.dev/

I can take a look at this

**Comment by lukasjhan** [comment]
> > @cre8 Yeah, we definitely use some framework that use headless chrome(or other browser)
> > How about trying this? https://playwright.dev/
> 
> I can take a look at this

Thank you :)

**Comment by lukasjhan** [comment]
I want to support Ed25519 and ES256 as JWK but,

browser - doesn't seem to support Ed25519 natively.
node - bad jwk support

I turned this PR to draft and keep working on it.

**Comment by lukasjhan** [comment]
In nodejs I used [webcrypto](https://nodejs.org/api/webcrypto.html#web-crypto-api)

but it is only support node >= 20. I tested in node 18 it failed.

**Comment by lukasjhan** [comment]
@cre8 Looks like test are working well ;)

**Comment by cre8** [comment]
@lukasjhan I think we need to support ES256 since it's the only algorithm supported by both platforms. Of course we can implement dozens of others, but in the first place we should have one algorithm people can use in both environments to sign and verify credentials.

Are you sure with the support? According to the docs webcrypto is supported since v15.

**Comment by lukasjhan** [comment]
@cre8 I applied your matrix check :) 
I remove Ed25519 in nodejs-crypto package. Like you said, At first let's supporting ES256

**Review by cre8 — APPROVED** [review]
LGTM

**Pull request merged**
