### PR TITLE
feat: calcuate sd_hash in kb JWT

### LINKED ISSUE #108: feat: calculate sd_hash automatically in present function
see: https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-07.html#section-5.3.1

sd_hash = `Hasher("<Issuer-signed JWT>~<Disclosure 1>~<Disclosure 2>~...~<Disclosure N>~", <algorithm from the disclosed JWT>)`

### PR DESCRIPTION
**Pull request by lukasjhan**
sd_hash is a base64url hash digest of the presented SD-JWT. So we can calculate that value in our logic.

It closes #108

### CODE REVIEW

**Comment by cre8** [comment]
@lukasjhan changes are looking good. Just fix the linting error and the PR is ready to be merged

**Comment by lukasjhan** [comment]
> @lukasjhan changes are looking good. Just fix the linting error and the PR is ready to be merged

I changed it :), I think my vscode has some kind of bug. It changed the indent automatically but not show the diff XD

**Comment by cre8** [comment]
A test for `createKBJwt` would also be nice

**Comment by lukasjhan** [comment]
> A test for `createKBJwt` would also be nice

Okay I'll add one :)

**Comment by lukasjhan** [comment]
@cre8  Deleted it because it was an unused function. It was my mistake. :)

**Comment by lukasjhan** [comment]
hmm.. 0.04%

**Pull request merged**
