### PR TITLE
Feat: select disclosure for present

### PR DESCRIPTION
**Pull request by lukasjhan**
I made a selectDisclosures function to select serialized Disclosures with PresentationFrame.
I didn't know there would be a use case like this, but PEX needs this function.

@cre8  I'm planning to integrate it in PEX right away, if it's merged after review, will I be able to distribute it as 0.4.1?

### CODE REVIEW

**Comment by cre8** [comment]
@lukasjhan LGTM, can you add the missing tests so codecov is happy?

Releasing a patch is fine for me

**Comment by lukasjhan** [comment]
> @lukasjhan LGTM, can you add the missing test so codecov is happy?
> 
> Releasing a patch is fine for me

Okay :)

**Comment by lukasjhan** [comment]
@cre8 I found that I can't reproduce error in this implementation. I think we can't cover that 4 lines of throw exception

**Comment by cre8** [comment]
@lukasjhan If we can not reproduce it, why are we checking it? :D

**Review by cre8 — APPROVED** [review]

**Comment by lukasjhan** [comment]
Thank you. I never think of that :)

**Pull request merged**
