### PR TITLE
[#3]Add MAINTAINERS.md

### PR DESCRIPTION
**Pull request by lukasjhan**
Issue: #3 

## Purpose

Add MAINTAINERS.md
Refer to https://tac.openwallet.foundation/governance/maintainers-file-content/

### CODE REVIEW

**Comment by lukasjhan** [comment]
@tkuhrt Do we have to fill in all the fields? or some of them can be blank?

**Review by tkuhrt — APPROVED** [review]
This is okay. 

In the long term, it would be great to get Ace and Gavin to join the OpenWallet Foundation Discord so that they can participate in discussions in the #sd-jwt-js channel. 

Also, there are a few SHOULDs in the [Maintainers File Content](https://tac.openwallet.foundation/governance/maintainers-file-content), including:
1. What Does Being a Maintainer Entail
2. How to Become a Maintainer
3. How Maintainers are Removed or Moved to Emeritus Status

Eventually, it would be great to see this information added.

**Comment by lukasjhan** [comment]
> In the long term, it would be great to get Ace and Gavin to join the OpenWallet Foundation Discord so that they can participate in discussions in the #sd-jwt-js channel.

They're probably on discord. I will ask them and add the IDs.

**Comment by lukasjhan** [comment]
> Also, there are a few SHOULDs in the [Maintainers File Content](https://tac.openwallet.foundation/governance/maintainers-file-content), including:
> 
> 1. What Does Being a Maintainer Entail
> 2. How to Become a Maintainer
> 3. How Maintainers are Removed or Moved to Emeritus Status

We'll discuss those topics and add the information

**Review by zustkeeper — APPROVED** [review]

**Review by zustkeeper — APPROVED** [review]

**Pull request merged**
